basePath: /api/v1
host: localhost:8080
info:
  contact:
    email: me@azmi.web.id
    name: Azmi
    url: https://www.azmi.web.id
  description: This is a simple E-Commerce API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: FinalProject GO API
  version: "0.1"
paths:
  /user/register:
    post:
      consumes:
      - application/json
      description: Register User
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: User registered successfully
      summary: Register User
      tags:
      - User
securityDefinitions:
  BearerToken:
    type: basic
swagger: "2.0"
